// @generated automatically by Diesel CLI.
//
// This file is normally auto-generated by `diesel migration run`.
// It is pre-created here so the project compiles before running migrations.
// After running `diesel migration run`, Diesel CLI will overwrite this file
// with the exact same content (derived from the actual database schema).
//
// IMPORTANT: Do NOT edit this file manually in production workflows.
// Always let `diesel migration run` regenerate it from the database.
// The table! macro generates Rust types (modules, structs, traits) that
// Diesel's query builder uses for compile-time SQL validation.

diesel::table! {
    products (id) {
        id -> Int4,
        name -> Varchar,
        price -> Numeric,
        category -> Nullable<Varchar>,
        stock -> Int4,
        created_at -> Timestamp,
    }
}

diesel::table! {
    orders (id) {
        id -> Int4,
        product_id -> Int4,
        quantity -> Int4,
        total_price -> Numeric,
        status -> Varchar,
        customer_email -> Nullable<Varchar>,
        created_at -> Timestamp,
    }
}

diesel::joinable!(orders -> products (product_id));
diesel::allow_tables_to_appear_in_same_query!(products, orders);
