# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryStub(object):
    """A simple inventory service demonstrating unary and server-streaming RPCs.
    Shared between the Rust server (tonic) and the Python client (grpcio).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddItem = channel.unary_unary(
                '/inventory.Inventory/AddItem',
                request_serializer=inventory__pb2.AddItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.AddItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/inventory.Inventory/GetItem',
                request_serializer=inventory__pb2.GetItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_stream(
                '/inventory.Inventory/ListItems',
                request_serializer=inventory__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=inventory__pb2.ListItemsResponse.FromString,
                _registered_method=True)


class InventoryServicer(object):
    """A simple inventory service demonstrating unary and server-streaming RPCs.
    Shared between the Rust server (tonic) and the Python client (grpcio).

    """

    def AddItem(self, request, context):
        """Unary: Add a new item to the inventory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Unary: Query a single item by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Server streaming: List all items in the inventory.
        The server sends each item as a separate message in the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=inventory__pb2.AddItemRequest.FromString,
                    response_serializer=inventory__pb2.AddItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=inventory__pb2.GetItemRequest.FromString,
                    response_serializer=inventory__pb2.GetItemResponse.SerializeToString,
            ),
            'ListItems': grpc.unary_stream_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=inventory__pb2.ListItemsRequest.FromString,
                    response_serializer=inventory__pb2.ListItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.Inventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.Inventory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inventory(object):
    """A simple inventory service demonstrating unary and server-streaming RPCs.
    Shared between the Rust server (tonic) and the Python client (grpcio).

    """

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.Inventory/AddItem',
            inventory__pb2.AddItemRequest.SerializeToString,
            inventory__pb2.AddItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.Inventory/GetItem',
            inventory__pb2.GetItemRequest.SerializeToString,
            inventory__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inventory.Inventory/ListItems',
            inventory__pb2.ListItemsRequest.SerializeToString,
            inventory__pb2.ListItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
