# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"?\n\x0e\x41\x64\x64ItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"/\n\x0f\x41\x64\x64ItemResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\x0eGetItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"@\n\x0fGetItemResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"\x12\n\x10ListItemsRequest\"B\n\x11ListItemsResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\x32\xd9\x01\n\tInventory\x12@\n\x07\x41\x64\x64Item\x12\x19.inventory.AddItemRequest\x1a\x1a.inventory.AddItemResponse\x12@\n\x07GetItem\x12\x19.inventory.GetItemRequest\x1a\x1a.inventory.GetItemResponse\x12H\n\tListItems\x12\x1b.inventory.ListItemsRequest\x1a\x1c.inventory.ListItemsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDITEMREQUEST']._serialized_start=30
  _globals['_ADDITEMREQUEST']._serialized_end=93
  _globals['_ADDITEMRESPONSE']._serialized_start=95
  _globals['_ADDITEMRESPONSE']._serialized_end=142
  _globals['_GETITEMREQUEST']._serialized_start=144
  _globals['_GETITEMREQUEST']._serialized_end=174
  _globals['_GETITEMRESPONSE']._serialized_start=176
  _globals['_GETITEMRESPONSE']._serialized_end=240
  _globals['_LISTITEMSREQUEST']._serialized_start=242
  _globals['_LISTITEMSREQUEST']._serialized_end=260
  _globals['_LISTITEMSRESPONSE']._serialized_start=262
  _globals['_LISTITEMSRESPONSE']._serialized_end=328
  _globals['_INVENTORY']._serialized_start=331
  _globals['_INVENTORY']._serialized_end=548
# @@protoc_insertion_point(module_scope)
