# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  Phase 5: Code generation script — embed a text file as a C++ string      ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# This CMake script is executed at BUILD TIME via add_custom_command().
# It reads a text file and generates a C++ header containing the file's
# contents as a constexpr string literal.
#
# Usage (from CMakeLists.txt):
#   add_custom_command(
#       OUTPUT ${OUTPUT_FILE}
#       COMMAND ${CMAKE_COMMAND} -DINPUT_FILE=... -DOUTPUT_FILE=... -P embed_file.cmake
#       DEPENDS ${INPUT_FILE}
#   )
#
# Input variables (set via -D on the cmake -P command line):
#   INPUT_FILE  — path to the text file to embed
#   OUTPUT_FILE — path to the generated .h file
#   VAR_NAME    — C++ variable name for the embedded string (default: "embedded_data")

# Validate inputs
if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "embed_file.cmake: INPUT_FILE not defined")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "embed_file.cmake: OUTPUT_FILE not defined")
endif()

if(NOT DEFINED VAR_NAME)
    set(VAR_NAME "embedded_data")
endif()

# Read the input file
file(READ "${INPUT_FILE}" file_content)

# Escape characters that would break a C++ raw string literal:
#   - We use R"DELIM(...)DELIM" syntax, so we only need to worry about
#     the delimiter appearing in the content (unlikely for "EMBED").
#   - No other escaping needed — that's the beauty of raw string literals.

# Get the input filename for the comment
get_filename_component(input_name "${INPUT_FILE}" NAME)

# Generate the header
file(WRITE "${OUTPUT_FILE}"
"// ┌──────────────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED by embed_file.cmake — DO NOT EDIT                        │
// │ Source: ${input_name}                                                    │
// └──────────────────────────────────────────────────────────────────────────┘
#ifndef EMBEDDED_${VAR_NAME}_H
#define EMBEDDED_${VAR_NAME}_H

#include <string_view>

namespace generated {

inline constexpr std::string_view ${VAR_NAME} = R\"EMBED(${file_content})EMBED\";

} // namespace generated

#endif // EMBEDDED_${VAR_NAME}_H
")

message(STATUS "Generated ${OUTPUT_FILE} from ${input_name} (var: ${VAR_NAME})")
