// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  Phase 3: Library target — implementation                                  ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

#include "greeter.h"
#include "config.h"  // Generated by configure_file (Phase 4)

#include <algorithm>
#include <string>
#include <vector>

Greeter::Greeter(std::string name) : name_(std::move(name)) {}

std::string Greeter::greet() const {
    // ── Exercise Context ──────────────────────────────────────────────────
    // This exercise shows how library implementation accesses CMake options.
    // The ENABLE_GREETING_EMOJI macro comes from configure_file (config.h).
    // This is how you make build-time toggles affect runtime behavior.

    // TODO(human): Return a greeting string.
    //
    // Requirements:
    //   1. Format: "Hello, <name>! My name is <name_>."
    //      where <name> is name_ (the greeter's name) — wait, re-read the header.
    //      Actually: "Hello from <name_>!" is simpler and correct.
    //
    //   2. If ENABLE_GREETING_EMOJI is 1, append " 👋" to the greeting.
    //      Use:  #if ENABLE_GREETING_EMOJI
    //
    // Example output:
    //   Greeter("Alice").greet()  →  "Hello from Alice!"
    //   Greeter("Alice").greet()  →  "Hello from Alice! 👋"  (if emoji enabled)
    //
    // Placeholder (compiles but needs your implementation):
    return "Hello from " + name_ + "!";
}

std::vector<std::string> Greeter::greet_many(const std::vector<std::string>& names) const {
    // ── Exercise Context ──────────────────────────────────────────────────
    // This exercise practices implementing library methods that consumers call.
    // Focus on clean C++ idioms; the CMake side (target linkage) is already set up.

    // TODO(human): For each name in `names`, produce a greeting string.
    //
    // Format: "Hey <name>, greetings from <name_>!"
    //
    // Hint: Use std::transform with a lambda, or a simple range-for loop.
    //       Push results into a vector and return it.
    //
    // Example:
    //   Greeter("Alice").greet_many({"Bob", "Eve"})
    //   → {"Hey Bob, greetings from Alice!", "Hey Eve, greetings from Alice!"}
    //
    // Placeholder (compiles but needs your implementation):
    std::vector<std::string> results;
    results.reserve(names.size());
    for (const auto& n : names) {
        results.push_back("Hey " + n + ", greetings from " + name_ + "!");
    }
    return results;
}
