# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "redis>=5.0",
# ]
# ///
"""Redis Streams with Consumer Groups.

Demonstrates Redis Streams as an append-only log with consumer groups
for cooperative message processing. Covers XADD, XREADGROUP, XACK,
and the Pending Entries List (PEL) for at-least-once delivery.

Run with Redis running (docker compose up -d):
    uv run src/06_redis_streams.py
"""

from __future__ import annotations

import asyncio
import json
import time

import redis.asyncio as aioredis


# ── Configuration ────────────────────────────────────────────────────

REDIS_URL = "redis://localhost:6379/0"
STREAM_KEY = "stream:076b:events"
CONSUMER_GROUP = "event-processors"


# ── TODO(human): Implement these functions ───────────────────────────


async def produce_events(
    r: aioredis.Redis,
    stream_key: str,
    events: list[dict],
) -> list[str]:
    """Produce events to a Redis Stream using XADD.

    # ── Exercise Context ──────────────────────────────────────────────────
    # XADD appends an entry to a Redis Stream. Each entry consists of:
    #   - An ID: auto-generated with '*' (format: <ms-timestamp>-<seq>)
    #   - A set of field-value pairs (like a flat dict)
    #
    # Redis Streams are append-only logs -- entries cannot be modified
    # after insertion (only deleted with XDEL or trimmed with XTRIM).
    # This immutability makes them suitable for event sourcing, audit
    # logs, and message queues.
    #
    # The auto-generated ID has useful properties:
    #   - Time-ordered: entries are always in chronological order
    #   - Unique: the sequence number disambiguates entries within the
    #     same millisecond
    #   - Comparable: you can range-query by timestamp
    #
    # Stream entries are different from Pub/Sub messages: they persist
    # in Redis and can be read by consumers that connect later. Pub/Sub
    # is fire-and-forget; Streams are durable.
    # ──────────────────────────────────────────────────────────────────────

    TODO(human): Add each event to the stream using XADD.

    Steps:
      1. Create an empty list to collect entry IDs:
             entry_ids = []

      2. For each event dict in the events list:
         a. Prepare the fields dict for XADD. Redis Stream entries are
            flat key-value pairs (both must be strings), so serialize
            the full event as a JSON string in a "data" field, and also
            include the "type" field for easy filtering:

                fields = {
                    "type": event.get("type", "unknown"),
                    "data": json.dumps(event),
                }

         b. Add the entry to the stream:
                entry_id = await r.xadd(stream_key, fields)

            Parameters:
              - stream_key: the stream name (e.g., "stream:076b:events")
              - fields: dict of field-value pairs to store
              - The default ID '*' is used (auto-generated timestamp-seq)

            Returns the entry ID (e.g., "1706123456789-0")

         c. Append entry_id to entry_ids.

      3. Return entry_ids (list of all generated entry IDs).

    Args:
        r: Async Redis client.
        stream_key: The Redis Stream key.
        events: List of event dicts to produce.

    Returns:
        List of entry IDs generated by Redis.

    Docs: https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.core.CoreCommands.xadd
    """
    raise NotImplementedError("TODO(human): Implement produce_events")


async def create_consumer_group(
    r: aioredis.Redis,
    stream_key: str,
    group_name: str,
    start_id: str = "0",
) -> bool:
    """Create a consumer group on a Redis Stream.

    # ── Exercise Context ──────────────────────────────────────────────────
    # Consumer groups enable multiple consumers to cooperatively process
    # a stream. Without consumer groups, every consumer sees EVERY message
    # (fan-out). With a consumer group, each message is delivered to
    # exactly ONE consumer in the group (load balancing / work distribution).
    #
    # The start_id parameter determines where the group starts reading:
    #   - "0" = from the beginning (all existing + new messages)
    #   - "$" = from now (only new messages, skip existing)
    #   - A specific ID = from that entry onward
    #
    # mkstream=True creates the stream if it doesn't exist. Without it,
    # XGROUP CREATE on a non-existent stream raises an error. This is
    # a common gotcha when setting up consumer groups in initialization
    # code that might run before any producer has written to the stream.
    #
    # Once created, the group tracks:
    #   - last-delivered-id: the ID of the last entry delivered to any consumer
    #   - Pending Entries List (PEL): entries delivered but not yet ACKed
    # ──────────────────────────────────────────────────────────────────────

    TODO(human): Create a consumer group on the stream.

    Steps:
      1. Try to create the consumer group:
             await r.xgroup_create(
                 stream_key,
                 group_name,
                 id=start_id,
                 mkstream=True,
             )

         Parameters:
           - stream_key: the stream to create the group on
           - group_name: name of the consumer group
           - id: starting position ("0" for all messages, "$" for new only)
           - mkstream: create the stream if it doesn't exist

      2. Return True on success.

      3. Handle the case where the group already exists. If the group
         was previously created, Redis raises a ResponseError with
         "BUSYGROUP Consumer Group name already exists". Catch this:
             except aioredis.ResponseError as e:
                 if "BUSYGROUP" in str(e):
                     return False  # Group already exists, not an error
                 raise  # Re-raise unexpected errors

    Args:
        r: Async Redis client.
        stream_key: The Redis Stream key.
        group_name: Name for the consumer group.
        start_id: Entry ID to start consuming from ("0" or "$").

    Returns:
        True if the group was created, False if it already existed.

    Docs: https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.core.CoreCommands.xgroup_create
    """
    raise NotImplementedError("TODO(human): Implement create_consumer_group")


async def consume_events(
    r: aioredis.Redis,
    stream_key: str,
    group_name: str,
    consumer_name: str,
    count: int = 5,
    block_ms: int = 2000,
) -> list[dict]:
    """Consume and acknowledge events from a Redis Stream consumer group.

    # ── Exercise Context ──────────────────────────────────────────────────
    # XREADGROUP is the consumer group version of XREAD. When you read
    # with XREADGROUP, Redis:
    #   1. Delivers the message to this specific consumer
    #   2. Adds it to the consumer's Pending Entries List (PEL)
    #   3. Will NOT deliver it to another consumer in the same group
    #
    # The special ID ">" means "give me only messages that have never
    # been delivered to any consumer in this group." This is the normal
    # operating mode. To re-read pending (unacknowledged) messages,
    # use "0" instead of ">" -- useful for crash recovery.
    #
    # XACK removes a message from the PEL, confirming that processing
    # is complete. This is the at-least-once delivery guarantee:
    #   - If a consumer reads a message and crashes before XACK,
    #     the message stays in the PEL
    #   - Another consumer can claim it via XCLAIM or XAUTOCLAIM
    #   - The message is only "done" when XACK is called
    #
    # This is analogous to Kafka's consumer offset commit: messages
    # are "in flight" until explicitly acknowledged.
    # ──────────────────────────────────────────────────────────────────────

    TODO(human): Read events with XREADGROUP and acknowledge them with XACK.

    Steps:
      1. Read messages from the consumer group:
             messages = await r.xreadgroup(
                 groupname=group_name,
                 consumername=consumer_name,
                 streams={stream_key: ">"},
                 count=count,
                 block=block_ms,
             )

         Parameters:
           - groupname: the consumer group name
           - consumername: unique name for this consumer within the group
           - streams: dict mapping stream key to ID (">" for new messages)
           - count: max messages to read in one call
           - block: milliseconds to block if no messages available (0=forever)

         Returns a list of [stream_key, [(entry_id, fields_dict), ...]]
         or an empty list if no messages available within the block timeout.

      2. Parse the results and acknowledge each message:
             processed = []
             if messages:
                 for stream_name, entries in messages:
                     for entry_id, fields in entries:
                         # Parse the event data
                         event_data = json.loads(fields.get("data", "{}"))
                         event_type = fields.get("type", "unknown")

                         # Acknowledge the message (removes from PEL):
                         await r.xack(stream_key, group_name, entry_id)

                         processed.append({
                             "entry_id": entry_id,
                             "type": event_type,
                             "data": event_data,
                             "consumer": consumer_name,
                         })

      3. Return the list of processed events.

    Args:
        r: Async Redis client.
        stream_key: The Redis Stream key.
        group_name: The consumer group name.
        consumer_name: Unique consumer identifier within the group.
        count: Maximum number of events to read per call.
        block_ms: Milliseconds to block waiting for new events.

    Returns:
        List of processed event dicts, each containing entry_id, type,
        data, and consumer name.

    Why block_ms?
      Blocking reads are more efficient than polling. The consumer sleeps
      until a new message arrives or the timeout expires, avoiding busy
      loops and reducing Redis load. Similar to Kafka's consumer.poll().
    """
    raise NotImplementedError("TODO(human): Implement consume_events")


# ── Demonstration (boilerplate) ──────────────────────────────────────


async def demo_basic_stream() -> None:
    """Demonstrate basic stream operations."""
    r = aioredis.from_url(REDIS_URL, decode_responses=True)

    try:
        # Clean up
        await r.delete(STREAM_KEY)

        print("=== Redis Streams: Basic Operations ===\n")

        # --- Produce events ---
        print("--- Producing Events ---")
        events = [
            {"type": "order.created", "order_id": "ORD-001", "customer": "Alice", "amount": 99.99},
            {"type": "order.created", "order_id": "ORD-002", "customer": "Bob", "amount": 149.50},
            {"type": "order.paid", "order_id": "ORD-001", "payment_method": "credit_card"},
            {"type": "order.shipped", "order_id": "ORD-001", "carrier": "FedEx", "tracking": "FX123"},
            {"type": "order.created", "order_id": "ORD-003", "customer": "Charlie", "amount": 29.99},
            {"type": "order.paid", "order_id": "ORD-002", "payment_method": "paypal"},
            {"type": "order.cancelled", "order_id": "ORD-003", "reason": "customer_request"},
            {"type": "order.shipped", "order_id": "ORD-002", "carrier": "UPS", "tracking": "UP456"},
        ]

        entry_ids = await produce_events(r, STREAM_KEY, events)
        print(f"  Produced {len(entry_ids)} events")
        for eid, evt in zip(entry_ids, events):
            print(f"    {eid}: {evt['type']}")

        # --- Stream info ---
        print(f"\n--- Stream Info ---")
        info = await r.xinfo_stream(STREAM_KEY)
        print(f"  Length: {info['length']}")
        print(f"  First entry: {info['first-entry']}")
        print(f"  Last entry: {info['last-entry']}")

    finally:
        await r.aclose()


async def demo_consumer_groups() -> None:
    """Demonstrate consumer group processing."""
    r = aioredis.from_url(REDIS_URL, decode_responses=True)

    try:
        # Clean up and re-produce
        await r.delete(STREAM_KEY)

        events = [
            {"type": "task", "task_id": f"TASK-{i:03d}", "payload": f"data_{i}"}
            for i in range(12)
        ]
        await produce_events(r, STREAM_KEY, events)
        print(f"\n=== Redis Streams: Consumer Groups ===\n")
        print(f"  Produced {len(events)} tasks to stream")

        # --- Create consumer group ---
        print("\n--- Creating Consumer Group ---")
        created = await create_consumer_group(r, STREAM_KEY, CONSUMER_GROUP, start_id="0")
        print(f"  Group '{CONSUMER_GROUP}' created: {created}")

        # Attempt to create again (should return False, not error)
        created_again = await create_consumer_group(r, STREAM_KEY, CONSUMER_GROUP)
        print(f"  Group '{CONSUMER_GROUP}' created again: {created_again} (expected: False)")

        # --- Consume with multiple consumers ---
        print("\n--- Consuming with 3 Consumers ---")
        consumer_results: dict[str, list[dict]] = {}

        for consumer_name in ["worker-A", "worker-B", "worker-C"]:
            processed = await consume_events(
                r, STREAM_KEY, CONSUMER_GROUP, consumer_name, count=5, block_ms=500
            )
            consumer_results[consumer_name] = processed
            print(f"  {consumer_name}: processed {len(processed)} events")
            for evt in processed:
                print(f"    {evt['entry_id']}: {evt['data'].get('task_id', 'unknown')}")

        # --- Verify: all events consumed exactly once ---
        all_task_ids = set()
        for results in consumer_results.values():
            for evt in results:
                task_id = evt["data"].get("task_id", "unknown")
                all_task_ids.add(task_id)

        total_processed = sum(len(r) for r in consumer_results.values())
        print(f"\n  Total events processed: {total_processed} (expected: {len(events)})")
        print(f"  Unique tasks: {len(all_task_ids)} (expected: {len(events)})")
        print(f"  No duplicates: {total_processed == len(all_task_ids)}")

        # --- Check PEL (should be empty after all XACK) ---
        print("\n--- Pending Entries List (PEL) ---")
        pending = await r.xpending(STREAM_KEY, CONSUMER_GROUP)
        print(f"  Pending entries: {pending['pending']}")
        print(f"  (Expected: 0 -- all messages acknowledged)")

        # --- Consumer group info ---
        print("\n--- Consumer Group Info ---")
        groups = await r.xinfo_groups(STREAM_KEY)
        for g in groups:
            print(f"  Group: {g['name']}, consumers: {g['consumers']}, "
                  f"pending: {g['pending']}, last-delivered: {g['last-delivered-id']}")

    finally:
        await r.aclose()


async def demo_pending_recovery() -> None:
    """Demonstrate PEL and crash recovery."""
    r = aioredis.from_url(REDIS_URL, decode_responses=True)

    try:
        stream = "stream:076b:recovery_demo"
        group = "recovery-group"
        await r.delete(stream)

        print(f"\n=== Redis Streams: Pending Entry Recovery ===\n")

        # Produce events
        events = [{"type": "work", "item": f"item-{i}"} for i in range(5)]
        await produce_events(r, stream, events)
        print(f"  Produced {len(events)} events")

        # Create group
        await create_consumer_group(r, stream, group, start_id="0")

        # Simulate: consumer reads but does NOT acknowledge (simulating crash)
        print("\n--- Simulating Consumer Crash (read without XACK) ---")
        messages = await r.xreadgroup(
            groupname=group,
            consumername="crashed-worker",
            streams={stream: ">"},
            count=3,
        )

        if messages:
            for _, entries in messages:
                for eid, fields in entries:
                    print(f"  crashed-worker read: {eid} (NOT acknowledged)")

        # Check PEL -- should have 3 pending
        pending = await r.xpending(STREAM_KEY if False else stream, group)
        print(f"\n  Pending entries after crash: {pending['pending']} (expected: 3)")

        # Recovery: another consumer claims and processes pending messages
        print("\n--- Recovery: Claiming Pending Entries ---")
        # Read pending messages (use "0" instead of ">" to get PEL entries)
        pending_msgs = await r.xreadgroup(
            groupname=group,
            consumername="crashed-worker",
            streams={stream: "0"},
            count=10,
        )
        if pending_msgs:
            for _, entries in pending_msgs:
                for eid, fields in entries:
                    # Now acknowledge them
                    await r.xack(stream, group, eid)
                    print(f"  Recovered and ACKed: {eid}")

        # Also consume the remaining 2 undelivered events
        remaining = await r.xreadgroup(
            groupname=group,
            consumername="recovery-worker",
            streams={stream: ">"},
            count=10,
            block=500,
        )
        if remaining:
            for _, entries in remaining:
                for eid, fields in entries:
                    await r.xack(stream, group, eid)
                    print(f"  recovery-worker processed: {eid}")

        # Final check
        pending = await r.xpending(stream, group)
        print(f"\n  Pending entries after recovery: {pending['pending']} (expected: 0)")

    finally:
        await r.aclose()


async def main() -> None:
    print("=" * 60)
    print(" Practice 076b: Redis Streams with Consumer Groups")
    print("=" * 60)
    print()
    await demo_basic_stream()
    await demo_consumer_groups()
    await demo_pending_recovery()
    print("\nDone.")


if __name__ == "__main__":
    asyncio.run(main())
